/**
 * /consultant Command Handler — Monthly Key Bot
 * ─────────────────────────────────────────────────────────────
 * Provides on-demand AI operations consultant reports.
 *
 * Commands:
 *  /consultant        — Full analysis since last weekly report
 *  /consultant today  — Today-only quick analysis
 *
 * Access: Admin and Top Management only.
 */

const log = require("../utils/logger");
const { isTeamAdmin, isHighPriority, resolveTeamMember } = require("../team-members");
const consultant = require("../services/consultant");

const DIV = "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━";

/**
 * Handle /consultant command.
 */
async function handleConsultant(ctx) {
  const username = ctx.from?.username?.toLowerCase();
  const threadId = ctx.message?.message_thread_id;

  // Access control: admin or high-priority only
  if (!isTeamAdmin(username) && !isHighPriority(username)) {
    return ctx.reply(
      `🔒 *Access restricted.*\nOnly CEO and Top Management can use this command.\n\n${DIV}\n\n🔒 *الوصول مقيد.*\nهذا الأمر متاح فقط للمدير التنفيذي والإدارة العليا.`,
      {
        parse_mode: "Markdown",
        ...(threadId ? { message_thread_id: threadId } : {}),
      }
    );
  }

  const args = (ctx.message.text || "").replace(/^\/consultant(?:@\S+)?\s*/, "").trim().toLowerCase();

  // Show "typing" indicator
  try {
    await ctx.telegram.sendChatAction(ctx.chat.id, "typing");
  } catch (e) { /* ignore */ }

  // Send a "generating" message
  const waitMsg = await ctx.reply(
    `🧠 *Generating consultant analysis...*\nThis may take 30-60 seconds.\n\n${DIV}\n\n🧠 *جاري إنشاء تحليل المستشار...*\nقد يستغرق ذلك ٣٠-٦٠ ثانية.`,
    {
      parse_mode: "Markdown",
      ...(threadId ? { message_thread_id: threadId } : {}),
    }
  );

  try {
    let result;

    if (args === "today" || args === "اليوم") {
      result = await consultant.generateTodayReport(ctx.telegram.token ? { telegram: ctx.telegram } : ctx);
    } else {
      result = await consultant.generateOnDemandReport(
        ctx.telegram.token ? { telegram: ctx.telegram } : ctx,
        threadId
      );
    }

    // Delete the "generating" message
    try {
      await ctx.telegram.deleteMessage(ctx.chat.id, waitMsg.message_id);
    } catch (e) { /* ignore */ }

    if (!result.success) {
      return ctx.reply(
        `❌ *Report generation failed.*\n${result.error || "Unknown error"}\n\n${DIV}\n\n❌ *فشل إنشاء التقرير.*\n${result.error || "خطأ غير معروف"}`,
        {
          parse_mode: "Markdown",
          ...(threadId ? { message_thread_id: threadId } : {}),
        }
      );
    }

    log.info("Consultant", `On-demand report generated by @${username}`);
  } catch (error) {
    log.error("Consultant", "Command handler error", { error: error.message });

    // Delete the "generating" message
    try {
      await ctx.telegram.deleteMessage(ctx.chat.id, waitMsg.message_id);
    } catch (e) { /* ignore */ }

    return ctx.reply(
      `❌ *Error generating report.*\n${error.message}\n\n${DIV}\n\n❌ *خطأ في إنشاء التقرير.*\n${error.message}`,
      {
        parse_mode: "Markdown",
        ...(threadId ? { message_thread_id: threadId } : {}),
      }
    );
  }
}

module.exports = {
  handleConsultant,
};
